services:
  fallback:
    build:
      context: .
    tty: true
    stdin_open: true
    network_mode: "host"
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      DIFFICULTY: "peaceful"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "256"
      VIEW_DISTANCE: "16"
      MODE: "adventure"
      SERVER_PORT: "25567"
      LEVEL_TYPE: "flat"
      CFG_PROXY_SECRET: "secret"
