hideOverlays = "RELOADING"
rgbProgress = true
blockOverlay = false
miniRender = false
enableScissor = false
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = true
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = false
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
