services:
  spectrum:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MEMORY: "8G"
      EULA: "TRUE"
      DIFFICULTY: "easy"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "16"
      VIEW_DISTANCE: "12"
      MODE: "survival"
      SERVER_PORT: "25567"
      SEED: "-2751134287749678599"
    network_mode: "host"
    volumes:
      - ./config:/data/config