services:
  spectrum:
    build:
      context: .
    tty: true
    stdin_open: true
    network_mode: "host"
    environment:
      MEMORY: "8G"
      EULA: "TRUE"
      DIFFICULTY: "easy"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "16"
      VIEW_DISTANCE: "12"
      MODE: "survival"
      SERVER_PORT: "25566"
      SEED: "-2751134287749678599"
      CFG_PROXY_SECRET: "secret"