name: Build resource packs

on:
  push:
    branches:
      - main
    paths:
      - resourcepacks/**
      - .github/workflows/resourcepacks.yml

permissions:
  contents: write
  packages: write

jobs:
  translations:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'translations.zip'
          directory: resourcepacks/translations

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "resourcepacks/translations/translations.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
          tag: translations-${{ github.event.head_commit.id }}
